
version: 2

sources:
      schema: "first dbt in database"
    tables:
      
      # On renomme les tables.
      - name: 
        identifier:raw_gz_product

      -name:sales
        identifier: raw_gz_sales

      -name:ship
        identifier: raw_gz_ship